### ISSUE TITLE
Update requirements.txt

### ISSUE THREAD

**Issue by spenpal** [PS1607/mbox-to-json#13]
I noticed the dependencies for this project are a bit outdated, given the required packages have a lot newer versions (for example, pandas now has 2.2.2).

The issue comes from when I create a virtual environment with Python 3.12, it takes ages for some reason to install pandas 1.4.2, when doing dependency resolution.

**Comment by vwkd** [comment]
Can confirm installation takes a long time. Running it also errors for me as described in #14.

**Comment by PS1607** [comment]
Updated requirements.txt
Recommended python version is 3.11
